Please fill out the information of your group!

| <p style="text-align: center;">First Name</p> | <p style="text-align: center;">Family Name</p> | Matr.-No. |
|----------------------------------------------|------------------------------------------------|-----------|
| <p style="text-align: left">Boran Cihan</p>  | <p style="text-align: left">Polat</p>          | k12005254 |
| <p style="text-align: left">*EDIT!*</p>      | <p style="text-align: left">*EDIT!*</p>        | *EDIT!*   |

<h2 style="text-align: center">344.105/6/7 UE: Natural Language Processing (WS2023/24)</h2>
<h1 style="color:rgb(0,120,170)">Assignment 2</h1>
<h2 style="color:rgb(0,120,170)">Getting to Know Word Embedding!</h2>

<b>Terms of Use</b><br>
This  material is prepared for educational purposes at the Johannes Kepler University (JKU) Linz, and is exclusively provided to the registered students of the mentioned course at JKU. It is strictly forbidden to distribute the current file, the contents of the assignment, and its solution. The use or reproduction of this manuscript is only allowed for educational purposes in non-profit organizations, while in this case, the explicit prior acceptance of the author(s) is required.

**Authors:** Navid Rekab-saz, Oleg Lesota<br>

<h2>Table of contents</h2>
<ol>
    <a href="#section-general-guidelines"><li style="font-size:large;font-weight:bold">General Guidelines</li></a>
    <a href="#section-taskA"><li style="font-size:large;font-weight:bold">Task A: Words Similarity and Nearest Neighbors (15 points)</li></a>
    <a href="#section-taskB"><li style="font-size:large;font-weight:bold">Task B: Document Classification with Word Embedding (15 points)</li></a>
    <a href="#section-taskC"><li style="font-size:large;font-weight:bold">Task C: Classification with sent2vec Document Embeddings (2 extra point)</li></a>
    <a href="#section-references"><li style="font-size:large;font-weight:bold">References</li></a>
    
</ol>

<a name="section-general-guidelines"></a><h2 style="color:rgb(0,120,170)">General Guidelines</h2>

### Assignment objective
The aim of this assignment is to get familiarized with using word embedding (WE) models in practice. The assignment in total has **30 points**; it also offers **2 extra points** which can cover any missing point.

This Notebook encompasses all aspects of the assignment, namely the descriptions of tasks as well as your solutions and reports. Feel free to add any required cell for solutions. The cells can contain code, reports, charts, tables, or any other material, required for the assignment. Feel free to provide the solutions in an interactive and visual way! 

Please discuss any unclear point in the assignment in the provided forum in MOODLE. It is also encouraged to provide answers to your peer's questions. However when submitting a post, keep in mind to avoid providing solutions. Please let the tutor(s) know shall you find any error or unclarity in the assignment.

### Libraries & Dataset

The assignment should be implemented with recent versions of `Python` (>3.7). Any standard Python library can be used, so far that the library is free and can be simply installed using `pip` or `conda`. Examples of potentially useful libraries are `scikit-learn`, `numpy`, `scipy`, `gensim`, `nltk`, `spaCy`, and `AllenNLP`. Use the latest stable version of each library.

To conduct the experiments, we use a subset of the `HumSet` dataset [1] (https://blog.thedeep.io/humset/). `HumSet` is created by the DEEP (https://www.thedeep.io) project – an open source platform which aims to facilitate processing of textual data for international humanitarian response organizations. The platform enables the classification of text excerpts, extracted from news and reports into a set of domain specific classes. The provided dataset contains the classes (labels) referring to the humanitarian sectors like agriculture, health, and protection. The dataset contains an overall number of 17,301 data points. 

Download the dataset from the Moodle page of the course.

the provided zip file consists of the following files:
- `thedeep.subset.train.txt`: Train set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.validation.txt`: Validation set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.test.txt`: Test set in csv format with three fields: sentence_id, text, and label.
- `thedeep.subset.label.txt`: Captions of the labels.
- `thedeep.ToU.txt`: Terms of use of the dataset.

[1] HumSet: Dataset of Multilingual Information Extraction and Classification for Humanitarian Crises Response
*Selim Fekih, Nicolo' Tamagnone, Benjamin Minixhofer, Ranjan Shrestha, Ximena Contla, Ewan Oglethorpe and Navid Rekabsaz.* 
In Findings of the 2022 Conference on Empirical Methods in Natural Language Processing (Findings of EMNLP), December 2022.


### Submission

Each group should submit the following two files:

- One Jupyter Notebook file (`.ipynb`), containing all the code, results, visualizations, etc. **In the submitted Notebook, all the results and visualizations should already be present, and can be observed simply by loading the Notebook in a browser.** The Notebook must be self-contained, meaning that (if necessary) one can run all the cells from top to bottom without any error. Do not forget to put in your names and student numbers in the first cell of the Notebook. 
- The HTML file (`.html`) achieved from exporting the Jupyter Notebook to HTML (Download As HTML).

You do not need to include the data files in the submission.

<a name="section-taskA"></a><h2 style="color:rgb(0,120,170)">Task A: Words Similarity and Nearest Neighbors (15 points)</h2>


**Loading a word embedding (WE) model (1 points).** Download a pre-trained word embedding model such as word2vec (https://code.google.com/archive/p/word2vec/) or GloVe (https://nlp.stanford.edu/projects/glove/). You can load the downloaded vectors into arrays, or use libraries such as `gensim` to download and process the vectors. 

**Calculating word-to-word similarities (4 points).** Select <ins>5 arbitrary words</ins> from 5 different topics like objects, science disciplines, verbs, adjectives, animals, etc. Let us refer to these words as *source words*. For each source word, calculate its cosine similarities to <ins>6 target words</ins>. The target words of each source word are also selected by you and should cover various levels of semantic relations – according to your linguistic judgement – to the source word, namely from highly-related to not related at all. Organize the target words in tables, such that the target words of each source word are sorted from the highest to the lowest relevance (according to your judgement). Consider the following points:

- **Implementation (2/4 points):** Implement cosine similarity as a function that takes two vectors and returns the similarity score. Implement cosine by yourself and do NOT use the provided functionalities of any library.
- **Reporting and observations (2/4 points):** Report the calculated similarities side by side with your word-to-word semantic relevance judgements in tables. Compare the results and report your observations.  

**Calculating nearest neighbors (10 points).** For the 5 source words, retrieve the $k=10$ nearest neighbors using the word embedding model, namely the words with the highest similarities to the source word. Consider the following points: 
    
- **Overall implementation (3/10 points):** your implemented function takes a source vector, a set of target vectors, and the $k$ parameter, and returns the $k$ nearest neighbors and their similarity scores. Implement nearest neighbor calculation by yourself and do NOT use the provided functionalities of any library.
- **Similarity metrics (2/10 points):** execute the calculation of nearest neighbors according to <ins>two similarity metrics</ins> namely cosine and dot product.
- **Efficiency (3/10 points):** your nearest neighbor functions should provide an *efficient* calculation of nearest neighbors. An inefficient way (which should be avoided!) would be looping over the set of vectors in the word embedding model, and one by one calculating the cosine/dot product similarity of the source vector to each of the target vectors. As a hint for an efficient way, consider that in `numpy` (and other libraries), calculating the dot product of a vector to a matrix is much faster than the dot products of the vector to each vector of the matrix.
- **Reporting and observations (2/10 points):** report the results in tables, which enable comparing between the outputs of the two similarity metrics. Which similarity metric would you prefer? Report your observations.

</div>

In [6]:
# Task A.1
import pandas as pd

# path to txt file
glove_file_path = "./glove.6B/glove.6B.50d.txt"

# creating Dataframe from the pre-trained word embedding
word_embedding_model  = pd.read_csv(glove_file_path, sep=" ", header=None, quoting=3)

# shows some tokens from data 
word_embedding_model[500:510]

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
500,working,0.257920,-0.14413,-0.035634,-0.605510,0.11004,-0.058799,-1.220900,-0.031605,-0.023699,...,-0.36178,-0.265340,0.42710,0.008118,0.198440,-0.385640,-0.35535,0.032932,-0.500550,0.54358
501,community,0.147740,0.62713,-0.818520,-0.168780,0.44055,-0.125150,-0.873690,-0.060084,0.488040,...,-0.47532,-0.519340,-0.32232,0.076290,-0.101320,0.477230,-0.83698,0.021588,-0.369720,0.14843
502,eight,0.069100,0.42247,0.677680,0.229440,0.40694,0.603520,-0.744310,0.257690,-0.245040,...,-0.85835,-0.196610,0.66630,0.123200,-0.046825,0.195420,-0.38691,-0.108340,-0.337410,-0.79467
503,groups,0.540970,-0.36081,-0.094686,-0.044767,0.19041,0.543940,-0.365790,-0.374030,-0.214830,...,-0.50889,-0.391390,0.10438,0.591870,1.012400,-0.470390,-1.15760,0.322480,-0.632440,-0.52289
504,despite,-0.032352,0.03639,-0.156780,-0.169620,-0.21591,0.285240,-0.374000,0.660930,-0.110300,...,-0.59646,-0.024493,-0.19373,0.009158,0.131400,0.024717,-0.31491,0.678600,-0.069295,-0.56524
505,level,-0.385000,1.03360,0.185520,-0.456380,0.28177,-0.817130,0.717090,-0.152060,0.118270,...,-0.47173,-0.560530,0.44492,0.354580,-0.401640,-0.350560,0.89285,0.662880,0.233850,-0.15513
506,largest,0.645900,0.13567,0.274030,1.116000,0.67439,0.013652,-0.927390,-0.262250,1.151800,...,-0.36453,-0.213520,0.16061,-0.098964,-0.016570,0.454650,-1.10410,0.180850,-0.136590,-0.71937
507,whose,0.284290,0.64750,-0.036221,-0.174420,0.99665,0.889780,-0.846160,-0.223290,-0.139650,...,-0.19889,0.772590,-0.22007,0.189580,0.013185,-0.249850,-0.63691,-0.353690,-0.144430,-0.28997
508,attacks,1.632800,-0.83160,0.749580,-0.244570,-0.11073,0.425210,0.253720,0.091321,0.049286,...,-0.60479,0.536990,0.28963,-0.586620,1.615900,-0.048896,-0.59347,0.872150,0.226500,-0.22236
509,germany,0.310980,0.05573,0.272930,-0.793540,0.15301,0.685470,-0.042667,0.232030,-0.909760,...,0.76412,-0.552710,1.56570,-1.409500,0.517190,0.404920,-0.07026,0.299400,-0.342460,-0.28954

In [7]:
# Task A.2
# Calculating word-to-word similarities
import numpy as np

# cosine similarity function
def cosine_similarity(vector_a, vector_b):
    
    dot_product = np.dot(vector_a, vector_b)
    
    norm_a = np.linalg.norm(vector_a)
    norm_b = np.linalg.norm(vector_b)
    
    similarity = dot_product / (norm_a * norm_b)
    return similarity

# Source words and their vectors
source_words = {
    'dog': word_embedding_model.loc[word_embedding_model[0] == 'dog'].to_numpy()[:, 1:][0],
    'car': word_embedding_model.loc[word_embedding_model[0] == 'car'].to_numpy()[:, 1:][0],
    'computer': word_embedding_model.loc[word_embedding_model[0] == 'computer'].to_numpy()[:, 1:][0],
    'happy': word_embedding_model.loc[word_embedding_model[0] == 'happy'].to_numpy()[:, 1:][0],
    'science': word_embedding_model.loc[word_embedding_model[0] == 'science'].to_numpy()[:, 1:][0]
}

# Target words for each source word
target_words = {
    'dog': ['puppy', 'cat', 'bark', 'running', 'vehicle', 'joyful'],
    'car': ['engine', 'road', 'puppy', 'computer', 'fast', 'sad'],
    'computer': ['software', 'mouse', 'happy', 'science', 'slow', 'animal'],
    'happy': ['joyful', 'sad', 'running', 'science', 'engine', 'puppy'],
    'science': ['physics', 'biology', 'running', 'software', 'engine', 'cat']
}

# Calculate and organize similarities
similarity_results = {}

for source_word, source_vector in source_words.items():
    similarities = []
    for target_word in target_words[source_word]:
        target_vector = word_embedding_model.loc[word_embedding_model[0] == target_word].to_numpy()[:, 1:][0]
        similarity_score = cosine_similarity(source_vector, target_vector)
        similarities.append((target_word, similarity_score))
    
    # Sorting target words based on similarity score
    similarities.sort(key=lambda x: x[1], reverse=True)
    similarity_results[source_word] = similarities

# Displaying the results
for source_word, similarities in similarity_results.items():
    print(f"Similarity Score for source word: {source_word}")
    print("-" * 19 + "Target Words" +"-" * 19)
    for target_word, similarity_score in similarities:
        seperater = np.round(44 - (len(target_word)))
        print(f"{target_word}" + " " * seperater + f"{similarity_score:.4f}")
    print("\n")

Similarity Score for source word: dog
-------------------Target Words-------------------
cat                                         0.9218
puppy                                       0.7755
bark                                        0.4867
running                                     0.4852
vehicle                                     0.4048
joyful                                      0.1320


Similarity Score for source word: car
-------------------Target Words-------------------
engine                                      0.6771
fast                                        0.5873
road                                        0.5845
computer                                    0.5121
sad                                         0.2568
puppy                                       0.1840


Similarity Score for source word: computer
-------------------Target Words-------------------
software                                    0.8815
science                                     0.6250
mouse                                       0.5243
slow                                        0.4575
animal                                      0.4066
happy                                       0.2806


Similarity Score for source word: happy
-------------------Target Words-------------------
sad                                         0.6891
joyful                                      0.5550
running                                     0.4938
puppy                                       0.4375
science                                     0.2296
engine                                      0.1920


Similarity Score for source word: science
-------------------Target Words-------------------
physics                                     0.8314
biology                                     0.8276
software                                    0.5255
running                                     0.4037
engine                                      0.2468
cat                                         0.2284

In [8]:
# Task A.3
# Nearest neighbors function
def nearest_neighbors(source_vector, target_vectors, k, similarity_metric='cosine'):
    
    if similarity_metric == 'cosine':
        # Calculate cosine similarity for all target vectors
        similarities = np.dot(target_vectors, source_vector) / (np.linalg.norm(target_vectors, axis=1) * np.linalg.norm(source_vector))
    elif similarity_metric == 'dot_product':
        # Calculate dot product similarity for all target vectors
        similarities = np.dot(target_vectors, source_vector)
    else:
        raise ValueError("Invalid similarity metric. Use 'cosine' or 'dot_product'")
   
    # Get indices of k nearest neighbors
    nearest_indices = np.argsort(similarities)[::-1][:k]
    return word_embedding_model.loc[nearest_indices]


# Calculate and display nearest neighbors using both similarity metrics
for source_word, source_vector in source_words.items():
    print(f"Nearest Neighbors for source word: {source_word}")
    
    # Remove the index column before calculating similarity
    word_embedding_vectors = word_embedding_model.iloc[:, 1:].to_numpy()
    
    # nearest_neighbors with cosine and dot product
    print("-" * 5 + " CosineSimilarity " + "-" * 7 + " DotProductSimilarity " + "-" * 5)
    
    cosine_neighbors = nearest_neighbors(source_vector, word_embedding_vectors, k=10, similarity_metric='cosine')
    dot_product_neighbors = nearest_neighbors(source_vector, word_embedding_vectors, k=10, similarity_metric='dot_product')
    
    
    max_length = max(cosine_neighbors[0].apply(len).max(), dot_product_neighbors[0].apply(len).max()) + 5
    
    for idx in range(10):  
        
        cosine_neighbor = cosine_neighbors.iloc[idx]
        cosine_similarity_score = cosine_similarity(source_vector, cosine_neighbor[1:].to_numpy())
        
        dot_neighbor = dot_product_neighbors.iloc[idx]
        dot_similarity_score = cosine_similarity(source_vector, dot_neighbor[1:].to_numpy())
        
        print(f"{cosine_neighbor[0]:<{max_length}} {cosine_similarity_score:.4f}"
              + "   |    " + 
              f"{dot_neighbor[0]:<{max_length}} {dot_similarity_score:.4f}")
    print("\n")

Nearest Neighbors for source word: dog
----- CosineSimilarity ------- DotProductSimilarity -----
dog         1.0000   |    dog         1.0000
cat         0.9218   |    dogs        0.8513
dogs        0.8513   |    you         0.6447
horse       0.7908   |    horse       0.7908
puppy       0.7755   |    cat         0.9218
pet         0.7725   |    your        0.6254
rabbit      0.7721   |    eat         0.6887
pig         0.7490   |    my          0.6372
snake       0.7399   |    boy         0.7383
baby        0.7396   |    girl        0.6774


Nearest Neighbors for source word: car
----- CosineSimilarity ------- DotProductSimilarity -----
car             1.0000   |    car             1.0000
truck           0.9209   |    cars            0.8870
cars            0.8870   |    truck           0.9209
vehicle         0.8834   |    vehicles        0.8175
driver          0.8464   |    vehicle         0.8834
driving         0.8384   |    driver          0.8464
bus             0.8211   |    bus             0.8211
vehicles        0.8175   |    trucks          0.7731
parked          0.7902   |    passenger       0.7788
motorcycle      0.7867   |    parked          0.7902


Nearest Neighbors for source word: computer
----- CosineSimilarity ------- DotProductSimilarity -----
computer          1.0000   |    computer          1.0000
computers         0.9165   |    computers         0.9165
software          0.8815   |    software          0.8815
technology        0.8526   |    technology        0.8526
electronic        0.8126   |    internet          0.8060
internet          0.8060   |    systems           0.7800
computing         0.8026   |    digital           0.7992
devices           0.8016   |    devices           0.8016
digital           0.7992   |    data              0.7605
applications      0.7913   |    online            0.7541


Nearest Neighbors for source word: happy
----- CosineSimilarity ------- DotProductSimilarity -----
happy           1.0000   |    'm              0.9142
'm              0.9142   |    i               0.8707
everyone        0.8976   |    you             0.8363
everybody       0.8965   |    me              0.8785
really          0.8840   |    we              0.8302
me              0.8785   |    n't             0.8354
definitely      0.8763   |    really          0.8840
maybe           0.8757   |    my              0.7992
'd              0.8718   |    're             0.8564
feel            0.8708   |    'll             0.8500


Nearest Neighbors for source word: science
----- CosineSimilarity ------- DotProductSimilarity -----
science         1.0000   |    science         1.0000
sciences        0.8548   |    university      0.7783
research        0.8437   |    research        0.8437
institute       0.8386   |    institute       0.8386
studies         0.8369   |    physics         0.8314
physics         0.8314   |    sciences        0.8548
psychology      0.8286   |    biology         0.8276
scientific      0.8285   |    studies         0.8369
biology         0.8276   |    professor       0.7772
studying        0.8099   |    psychology      0.8286

<a name="section-taskB"></a><h2 style="color:rgb(0,120,170)">Task B: Document Classification with WE (15 points)</h2>


This task follows the same instruction for document classification as provided in Assignment 1. You are indeed free to reuse any part of your code in Assignment 1 for this task. In Assignment 1, the representation of each document was created using a bag of words representation followed by dimensionality reduction. In this task, the document representations are created from the pre-trained word embeddings.

**Map word embeddings to dictionary words (5 points).** For every word in the dictionary (as discussed and created in Assignment 1), fetch the corresponding word embedding from the pre-trained model. If no embedding is found, initialize the corresponding word embedding randomly.

**Document embedding as the average of word embeddings (5 points).** Using the word embeddings, the representation of each document is defined as the *mean of the vectors of each document's words*. In particular, given the document $d$, consisting of words $\left[ v_1, v_2, ..., v_{|d|} \right]$, the document representation $\mathbf{e}_d$ is defined as:

$\mathbf{e}_d = \frac{1}{|d|}\sum_{i=1}^{|d|}{\mathbf{e}_{v_i}}$

where $\mathbf{e}_{v}$ is the vector of the word $v$, and $|d|$ is the length of the document.

**Classification and evaluation (5 points)** Using these new document representations, apply <ins>three classification algorithms</ins> and report the evaluation results (based on accuracy metric) on the test set.

In [60]:
#Task B.1

# importing dictionary from assignment 1
dictionary_with_threshold = pd.read_json("./dic.json", typ='series').to_dict().values()

def initialize_random_embedding(embedding_dim):
    return np.random.rand(embedding_dim)

embedding_dim = 50
word_embeddings_mapping = {}

for word in dictionary_with_threshold:
    word_embeddings_mapping[word] = word_embedding_model.get(word, initialize_random_embedding(embedding_dim))

df_word_embeddings = pd.DataFrame(list(word_embeddings_mapping.items()), columns=['word', 'embedding'])
df_word_embeddings.head()

       word                                          embedding
0     <num>  [0.996765145044449, 0.7835033982464372, 0.0103...
1      case  [0.9584810841467727, 0.025820100068983054, 0.0...
2      food  [0.9951854560118555, 0.471560526184569, 0.8502...
3    people  [0.951740893502633, 0.9295714424983795, 0.4840...
4  reported  [0.927238519018978, 0.054205456526171814, 0.31...

In [75]:
# reusing code from assignment 1 

from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

def stem_words(list_of_tokens: []):
    ps = PorterStemmer()
    
    stem_words = []
    for word in list_of_tokens:
        if word != "<num>" or word != "<dates>":
            stem_words.append(ps.stem(word))
        else:
            stem_words.append(word)
    return stem_words

def lem_words(list_of_tokens: []):
    lemmatizer = WordNetLemmatizer()
    lem_words = []
    for word in list_of_tokens:
        if word != "<num>" or word != "<dates>":
            lem_words.append(lemmatizer.lemmatize(word))
        else:
            lem_words.append(word)
            
    return lem_words

def tokenization(text: pd.Series, normalization_method: str = "lem"):
    corpus = []
    for sentence in text:
        # not using word_tokenize, because i want to have "<num>" and not "<","num", ">"
        corpus.append(sentence.split())
        
    list_of_words = np.concatenate(corpus)
    # gets normalized with one of the methods
    # default method is lem_words
    if normalization_method == "lem":
        return lem_words(list_of_words), corpus
    else:
        return stem_words(list_of_words), corpus


# Task B.2

def document_embedding(text: pd.Series, word_embeddings_mapping, normalization_method: str = "lem"):
    _, corpus = tokenization(text, normalization_method)
    
    document_embeddings = []
    for words in corpus:
        word_embeddings = [word_embeddings_mapping.get(word, np.zeros(embedding_dim)) for word in words]
        document_embedding = np.mean(word_embeddings, axis=0)
        
        document_embeddings.append(document_embedding)
    
    df_document_embeddings = pd.DataFrame(document_embeddings)
    return df_document_embeddings

In [83]:
load_train_text = pd.read_csv("nlp2023_24_data/thedeep.subset.train.txt", header=None, names=["Number", "Text", "Label"])
load_validation_text = pd.read_csv("nlp2023_24_data/thedeep.subset.validation.txt", header=None, names=["Number", "Text", "Label"])
load_test_text = pd.read_csv("nlp2023_24_data/thedeep.subset.test.txt", header=None, names=["Number", "Text", "Label"])

df_document_embeddings_train = document_embedding(load_train_text["Text"], word_embeddings_mapping)
df_document_embeddings_test = document_embedding(load_test_text["Text"], word_embeddings_mapping)
df_document_embeddings_validation = document_embedding(load_validation_text["Text"], word_embeddings_mapping)

In [84]:
df_document_embeddings_train.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.156600,0.132256,0.133079,0.165611,0.158178,0.078130,0.138361,0.175952,0.151938,0.143759,...,0.168230,0.159832,0.118003,0.206751,0.189982,0.164066,0.200458,0.171551,0.193531,0.140027
1,0.144676,0.105898,0.140664,0.113901,0.143011,0.121170,0.166157,0.165209,0.171732,0.159781,...,0.132856,0.105500,0.150371,0.132467,0.084834,0.160395,0.161684,0.111276,0.147504,0.144784
2,0.185262,0.187907,0.172386,0.217038,0.192446,0.171991,0.205100,0.164511,0.211433,0.160179,...,0.151791,0.207825,0.192762,0.198002,0.172767,0.203816,0.220385,0.194297,0.155268,0.234270
3,0.144637,0.157685,0.167629,0.130750,0.146390,0.128171,0.172260,0.154813,0.157850,0.173951,...,0.184242,0.162732,0.171678,0.173256,0.107365,0.197721,0.200501,0.135966,0.161513,0.160239
4,0.192376,0.153026,0.191389,0.164415,0.202197,0.167537,0.226054,0.212967,0.203276,0.175950,...,0.174590,0.175654,0.191278,0.217191,0.186444,0.194321,0.223586,0.156868,0.181414,0.206594

In [85]:
df_document_embeddings_test.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.093632,0.061790,0.098261,0.030696,0.096028,0.069387,0.218647,0.179806,0.115669,0.160049,...,0.153656,0.075566,0.108369,0.210689,0.041025,0.135565,0.183366,0.068212,0.081372,0.091427
1,0.159144,0.147065,0.151830,0.195143,0.156825,0.179783,0.188519,0.195054,0.206861,0.187544,...,0.160095,0.149042,0.170788,0.167623,0.150788,0.161134,0.193292,0.176356,0.184943,0.181627
2,0.130589,0.141424,0.159797,0.182785,0.148252,0.169103,0.148798,0.174537,0.153332,0.134749,...,0.153829,0.173832,0.149027,0.122668,0.166671,0.158471,0.152380,0.120610,0.152751,0.149370
3,0.168414,0.127308,0.126456,0.139888,0.120589,0.148847,0.155740,0.133512,0.159578,0.156286,...,0.129915,0.152447,0.131066,0.136704,0.124317,0.129707,0.141185,0.149756,0.141812,0.150031
4,0.130210,0.094254,0.125224,0.163299,0.191258,0.061743,0.109711,0.105842,0.127377,0.121865,...,0.082038,0.199271,0.135271,0.176286,0.106483,0.089990,0.148658,0.119507,0.143071,0.108778

In [86]:
df_document_embeddings_validation.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.122496,0.146682,0.079447,0.118995,0.154642,0.125361,0.102905,0.177013,0.244568,0.195179,...,0.162032,0.139849,0.147145,0.173005,0.109329,0.147060,0.167707,0.136861,0.122655,0.185031
1,0.196970,0.199167,0.202076,0.164944,0.163556,0.145935,0.194127,0.180391,0.163345,0.218902,...,0.179004,0.207654,0.216536,0.186070,0.177909,0.168790,0.204016,0.167093,0.205046,0.189770
2,0.182761,0.151862,0.190072,0.173348,0.202534,0.187642,0.158631,0.212294,0.148734,0.189746,...,0.194162,0.155520,0.151422,0.189989,0.155787,0.173503,0.162140,0.177811,0.146916,0.179755
3,0.147345,0.130768,0.134517,0.161209,0.147282,0.124602,0.179004,0.167971,0.132083,0.181305,...,0.134482,0.146974,0.102979,0.179936,0.151159,0.179506,0.164689,0.144024,0.129449,0.128624
4,0.123871,0.110495,0.112347,0.122801,0.123162,0.120822,0.155627,0.108823,0.108027,0.126101,...,0.109460,0.076072,0.103750,0.117990,0.136065,0.129074,0.102884,0.105639,0.103508,0.111517

In [88]:
#Task B.3   

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

y_train = load_train_text["Label"]
y_validation = load_validation_text["Label"]
y_test = load_test_text["Label"]

# Logistic Regression
lr = LogisticRegression(max_iter=1000)
lr.fit(df_document_embeddings_train, y_train)
lr_predictions = lr.predict(df_document_embeddings_validation)
lr_accuracy = accuracy_score(y_validation, lr_predictions)
print(f'Logistic Regression Accuracy on Validation Set: {lr_accuracy}')

# Random Forest
rf = RandomForestClassifier()
rf.fit(df_document_embeddings_train, y_train)
rf_predictions = rf.predict(df_document_embeddings_validation)
rf_accuracy = accuracy_score(y_validation, rf_predictions)
print(f'Random Forest Accuracy on Validation Set: {rf_accuracy}')

# Support Vector Machine
svc = SVC()
svc.fit(df_document_embeddings_train, y_train)
svc_predictions = svc.predict(df_document_embeddings_validation)
svc_accuracy = accuracy_score(y_validation, svc_predictions)
print(f'Support Vector Machine Accuracy on Validation Set: {svc_accuracy}')

Logistic Regression Accuracy on Validation Set: 0.43759630200308164
Random Forest Accuracy on Validation Set: 0.43682588597842836
Support Vector Machine Accuracy on Validation Set: 0.48536209553158705

In [89]:
# Logistic Regression
lr_predictions_test = lr.predict(df_document_embeddings_test)
lr_accuracy_test = accuracy_score(y_test, lr_predictions_test)
print(f'Logistic Regression Accuracy on Test Set: {lr_accuracy_test}')

# Random Forest
rf_predictions_test = rf.predict(df_document_embeddings_test)
rf_accuracy_test = accuracy_score(y_test, rf_predictions_test)
print(f'Random Forest Accuracy on Test Set: {rf_accuracy_test}')

# Support Vector Machine
svc_predictions_test = svc.predict(df_document_embeddings_test)
svc_accuracy_test = accuracy_score(y_test, svc_predictions_test)
print(f'Support Vector Machine Accuracy on Test Set: {svc_accuracy_test}')

Logistic Regression Accuracy on Test Set: 0.45394990366088633
Random Forest Accuracy on Test Set: 0.4350674373795761
Support Vector Machine Accuracy on Test Set: 0.5063583815028901

<a name="section-taskC"></a><h2 style="color:rgb(0,120,170)">Task C: Classification with sent2vec Document Embeddings (2 extra point)</h2>


Sent2vec [1] suggests another unsupervised approach to creating document embeddings from the underlying word embeddings. First, using the provided code in the paper, train a sendtvec model on the training set to create document embeddings. Then, repeat Task B while using the document embeddings provided by sent2vec. Similar to Task 2, conduct the classification experiments and report evaluation results.

[1] M. Pagliardini, P. Gupta, and M. Jaggi. Unsupervised Learning of Sentence Embeddings using Compositional n-Gram Features. In Proceedings of the conference of the North American Chapter of the Association for Computational Linguistics (NAACL), 2018.